[theme]
primaryColor="#47C7DA"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"

# Opt out of usage statistics collected by streamlit 
[browser]
gatherUsageStats=false